// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAcNS7SQKpiMlrHBk8xJ6IkuNt1C_rcuQ',
    appId: '1:644069241628:web:0960bd6b424598b80980d9',
    messagingSenderId: '644069241628',
    projectId: 'army-9cd13',
    authDomain: 'army-9cd13.firebaseapp.com',
    storageBucket: 'army-9cd13.firebasestorage.app',
    measurementId: 'G-0BVJ3FPC92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkVN7CPpyJHLiTiqGIeCo5z_aV6KzlBv8',
    appId: '1:644069241628:android:f9e7a587dcba91920980d9',
    messagingSenderId: '644069241628',
    projectId: 'army-9cd13',
    storageBucket: 'army-9cd13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo368eRz-Wx11ONvZSKG_nNad7OwPcY2c',
    appId: '1:644069241628:ios:c28fb6c1ec9ace5b0980d9',
    messagingSenderId: '644069241628',
    projectId: 'army-9cd13',
    storageBucket: 'army-9cd13.firebasestorage.app',
    iosBundleId: 'com.prayerblessedpath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo368eRz-Wx11ONvZSKG_nNad7OwPcY2c',
    appId: '1:644069241628:ios:ff91e095c3bcf0760980d9',
    messagingSenderId: '644069241628',
    projectId: 'army-9cd13',
    storageBucket: 'army-9cd13.firebasestorage.app',
    iosBundleId: 'com.onetwentyarmyprayer2.app.onetwentyarmyprayer2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAcNS7SQKpiMlrHBk8xJ6IkuNt1C_rcuQ',
    appId: '1:644069241628:web:7843a968d45140220980d9',
    messagingSenderId: '644069241628',
    projectId: 'army-9cd13',
    authDomain: 'army-9cd13.firebaseapp.com',
    storageBucket: 'army-9cd13.firebasestorage.app',
    measurementId: 'G-VDT0H01E57',
  );

}